import Head from "next/head";
import Image from "next/image";
import { useEffect, useState, useRef } from "react";
import styles from "../../styles/Home.module.css";

import ReactFullpage from "@fullpage/react-fullpage"; // will return static version on server and "live" version on client
import cn from "classnames";
import Lottie from "lottie-react";

import Logo from "../../public/logo.svg";
import CloseIcon from "../../public/close-x.svg";
import RightArrow from "../../public/right-arrow.svg";
import NormalMethod from "../../public/normal-method-icon.svg";
import FusionMethod from "../../public/fusion-method-icon.svg";
import ScrollDownWhite from "../../public/scroll-down.json";
import ScrollDownBlack from "../../public/scroll-down-black.json";
import LinkShare from "../../public/share-link.svg";
import TwitterShare from "../../public/share-twitter.svg";
import FacebookShare from "../../public/share-facebook.svg";
import InstagramShare from "../../public/share-instagram.svg";

import BiblePassage from "../components/BiblePassage";

export default function Home() {
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [readingMethod, setReadingMethod] = useState("normal");
  const [colorMode, setColorMode] = useState("dark");
  const [scrollProgress, setScrollProgress] = useState(0);
  const refContainer = useRef();

  const onScroll = () => {
    if (refContainer.current) {
      const { scrollTop, scrollHeight, clientHeight } = refContainer.current;
      console.log(scrollTop, scrollHeight - clientHeight, clientHeight);
      const percentY = scrollTop / (scrollHeight - clientHeight);
      const progress = Math.min(Math.floor(percentY * 17), 16);
      console.log(progress);
      setScrollProgress(progress);
    }
  };

  useEffect(() => {
    document.documentElement.setAttribute("data-theme", colorMode);
  }, [colorMode]);

  useEffect(() => {
    setScrollProgress(0);
  }, [readingMethod]);

  return (
    <div className={cn("pagePadding", styles.container)}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={cn(
          styles.settingsHover,
          isSettingsOpen ? styles.disappear : null
        )}
        onClick={() => setIsSettingsOpen(true)}
      >
        <div className={styles.settingsTextWrapper}>
          <div className={styles.settingsText}>Settings</div>
          <RightArrow />
        </div>
      </div>

      <div
        className={cn(
          styles.settingsWrapper,
          isSettingsOpen ? styles.settingsAppear : null
        )}
      >
        <div
          className={styles.closeButton}
          onClick={() => setIsSettingsOpen(false)}
        >
          Close
          <CloseIcon />
        </div>
        <div className={styles.settingOptionsWrapper}>
          <div
            className={cn(
              styles.settingOptionBlock,
              styles.settingOptionTop,
              readingMethod == "fusion" ? styles.active : null
            )}
            onClick={() => setReadingMethod("fusion")}
          >
            <FusionMethod />
            Fusion
          </div>
          <div
            className={cn(
              styles.settingOptionBlock,
              styles.settingOptionBottom,
              readingMethod == "normal" ? styles.active : null
            )}
            onClick={() => setReadingMethod("normal")}
          >
            <NormalMethod />
            Normal
          </div>
        </div>
        <div className={styles.settingOptionsWrapper}>
          <div
            className={cn(
              styles.settingOptionBlock,
              styles.settingOptionTop,
              colorMode == "dark" ? styles.active : null
            )}
            onClick={() => setColorMode("dark")}
          >
            <div className={styles.innerCircle}>
              {colorMode == "dark" ? (
                <div className={styles.outerCircle}></div>
              ) : null}
            </div>
            Dark
          </div>
          <div
            className={cn(
              styles.settingOptionBlock,
              styles.settingOptionBottom,
              colorMode == "light" ? styles.active : null
            )}
            onClick={() => setColorMode("light")}
          >
            <div className={cn(styles.innerCircle, styles.whiteCircle)}>
              {colorMode == "light" ? (
                <div className={styles.outerCircle}></div>
              ) : null}
            </div>
            Light
          </div>
        </div>
      </div>

      <ReactFullpage
        //fullpage options
        licenseKey={"YOUR_KEY_HERE"}
        scrollingSpeed={1000} /* Options here */
        scrollOverflow={true}
        keyboardScrolling={true}
        anchors={["1", "2", "3", "4"]}
        render={({ state, fullpageApi }) => {
          return (
            <ReactFullpage.Wrapper>
              <div className={cn("section", "fp-noscroll")}>
                <div className={styles.studyIntro}>
                  <div>
                    <Logo />
                  </div>
                  <div>
                    <div className="text-size-s">Todays Study</div>
                    <div className="text-size-xl">Romans 8:1-28</div>
                  </div>
                  <div className={styles.scrollDownWrapper}>
                    <div className="text-size-xs">Scroll to begin study</div>
                    <Lottie
                      className={styles.scrollDown}
                      loop={true}
                      animationData={
                        colorMode == "dark" ? ScrollDownWhite : ScrollDownBlack
                      }
                    />
                  </div>
                </div>
              </div>
              <div
                ref={refContainer}
                className={cn("section", styles.passageSection)}
                onScroll={onScroll}
              >
                <BiblePassage
                  scrollProgress={scrollProgress}
                  method={readingMethod}
                />
              </div>
              <div className={cn("section", "fp-noscroll")}>
                <div className={cn(styles.questionWrapper, "text-size-l")}>
                  Spend a few moments thinking through what you just read.
                </div>
                <div className={styles.absoluteScrollDown}>
                  <Lottie
                    className={styles.scrollDown}
                    loop={true}
                    animationData={
                      colorMode == "dark" ? ScrollDownWhite : ScrollDownBlack
                    }
                  />
                </div>
              </div>
              <div className={cn("section", "fp-noscroll")}>
                <div className={cn(styles.shareWrapper)}>
                  <div className={cn(styles.shareTop, "text-size-s")}>
                    Daily Growth from God’s Word.
                  </div>
                  <div className={styles.shareMiddle}>
                    <div className="text-size-l">Be the light, share.</div>
                    <div className={styles.shareLinksWrapper}>
                      <button className={cn(styles.button, styles.shareButton)}>
                        <LinkShare />
                      </button>
                      <button className={cn(styles.button, styles.shareButton)}>
                        <TwitterShare />
                      </button>
                      <button className={cn(styles.button, styles.shareButton)}>
                        <FacebookShare />
                      </button>
                      <button className={cn(styles.button, styles.shareButton)}>
                        <InstagramShare />
                      </button>
                    </div>
                  </div>
                  <div className={cn(styles.shareBottom, "text-size-xs")}>
                    http://lifewisdom.com/12301012BD
                  </div>
                </div>
              </div>
            </ReactFullpage.Wrapper>
          );
        }}
      />
    </div>
  );
}
